# Generated by Django 3.2.12 on 2022-03-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_achievements_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studcred',
            table='adminsite_studcred',
        ),
    ]
