 # Generated by Django 3.2.12 on 2022-04-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_alter_studcred_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='admissiondetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('HSC', models.CharField(blank=True, max_length=45, null=True)),
                ('CET', models.CharField(blank=True, max_length=45, null=True)),
                ('JEE', models.CharField(blank=True, max_length=45, null=True)),
                ('diploma', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'admission',
                'managed': False,
            },
        ),
    ]
